version: "3"
services:
  elevator: 
    build:
      context: .
    image: "contactless-elevator"
    container_name: "contactless-elevator"
    ports:
      - ${PORT}:${PORT}

  mediaserver:
    build:
      context: ./nxvms-docker
      args:
        COMPANY: ${COMPANY}
        MEDIASERVER_DEB: ${MEDIASERVER_URL}
    image: metavms-server:${MEDIASERVER_VERSION}
    container_name: mediaserver
    user: ${COMPANY}
    ports:
      - ${MEDIASERVER_PORTS}
    volumes:
      - ${VOLUMES_PATH}/etc:/opt/${COMPANY}/mediaserver/etc
      - ${VOLUMES_PATH}/var:/opt/${COMPANY}/mediaserver/var
      - ${VOLUMES_PATH}/nx_ini:/home/${COMPANY}/.config/nx_ini
      - ${VOLUMES_PATH}/entrypoint.d:/opt/mediaserver/entrypoint.d
      - ${VOLUMES_PATH}/recordings:/recordings
      - ${VOLUMES_PATH}/tmp:/tmp

  mediaserver-root-tool:
    image: metavms-server:${MEDIASERVER_VERSION}
    container_name: root_tool
    user: root
    command: ["/opt/${COMPANY}/mediaserver/bin/root-tool"]
    volumes:
      - ${VOLUMES_PATH}/tmp:/tmp
